jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Descargar cÃ³digo del repo
        uses: actions/checkout@v4

      - name: ğŸ“‚ Subir archivos por FTP (prueba con valores directos)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: "178.16.128.32"  # Ponlo manualmente para probar
          username: "u128332784.marcgranellhd2"
          password: "210700Responde*"
          local-dir: "./"
          server-dir: "/public_html/wp-content/plugins/testgitplugin"
          protocol: ftp
          passive: true
