name: Deploy Plugin to FTP

on:
  push:
    branches:
      - main  # Se ejecutarÃ¡ en cada push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Descargar cÃ³digo del repo
        uses: actions/checkout@v4

      - name: ğŸ“‚ Instalar lftp y subir archivos
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -u "u128332784.marcgranellhd2,210700Responde*" -e "
          set ftp:ssl-allow yes;
          set ftp:passive-mode yes;
          mirror -R ./ /public_html/wp-content/plugins/testgitplugin;
          bye;
          " 178.16.128.32
